NUM_OF_DEADLOCK_RETRIES = 1000
NUM_OF_MOVES_PER_GAME = 5

NORMAL_BOARD_SIZE = (5, 5)
NORMAL_COLOR_RANGE = 6
NORMAL_REPEAT = 1
NORMAL_AGENT = "random-agent"

EXP_REPEAT = 100
EXP_SAME_BOARD_REPEAT = 5
EXP_DIFF_BOARD_REPEAT = 20
