NUM_OF_DEADLOCK_RETRIES = 1000
NUM_OF_MOVES_PER_GAME = 20

NORMAL_BOARD_SIZE = (7, 7)
NORMAL_COLOR_RANGE = 6
NORMAL_REPEAT = 1
NORMAL_AGENT = "bottom-agent"

EXP_REPEAT = 10000
EXP_SAME_BOARD_REPEAT = 50
EXP_DIFF_BOARD_REPEAT = 200
